### ISSUE TITLE
Problem with renewing of certificates on 0.0.22

### ISSUE THREAD

**Issue by raczkow** [cybercinch/certbot-dns-directadmin#6]
I can't renew my certifictates after upgrade to 0.0.22:
```
Encountered exception during recovery: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python3/dist-packages/certbot_dns_directadmin/dns_directadmin.py", line 57, in _perform
    self._get_directadmin_client().add_txt_record(validation_domain_name, validation)
  File "/usr/lib/python3/dist-packages/certbot_dns_directadmin/dns_directadmin.py", line 83, in add_txt_record
    (directadmin_zone, directadmin_name) = self._get_zone_and_name(record_name)
  File "/usr/lib/python3/dist-packages/certbot_dns_directadmin/dns_directadmin.py", line 129, in _get_zone_and_name
    logger.debug('Suffix: ' + suffix)
NameError: name 'suffix' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/error_handler.py", line 108, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 323, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/lib/python3/dist-packages/certbot_dns_directadmin/dns_directadmin.py", line 60, in _cleanup
    self._get_directadmin_client().del_txt_record(validation_domain_name, validation)
  File "/usr/lib/python3/dist-packages/certbot_dns_directadmin/dns_directadmin.py", line 103, in del_txt_record
    (directadmin_zone, directadmin_name) = self._get_zone_and_name(record_name)
  File "/usr/lib/python3/dist-packages/certbot_dns_directadmin/dns_directadmin.py", line 129, in _get_zone_and_name
    logger.debug('Suffix: ' + suffix)
NameError: name 'suffix' is not defined
Attempting to renew cert (amazon.ncab.dev) from /etc/letsencrypt/renewal/amazon.ncab.dev.conf produced an unexpected error: name 'suffix' is not defined. Skipping.
```

Changing 129 line in `dns_directadmin.py` fix the issue:
```
- logger.debug('Suffix: ' + suffix)
+ logger.debug('Suffix: ' )
```

**Comment by guisea** [comment]
Thanks @raczkow Apologies I have been having some medical dramas so taken me a bit to look at this.  You were quite right about that line.  Removed it entirely as that was for a module no longer in use.  New version has been tested and pushed.
